name: unittest

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cargo build
        run: cargo build

      - name: cargo test
        run: cargo test
